# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68106d25edb7791a0e1951aa105a4bdaef0be88e8a7be0506d29b82c1eea4c469a1021fa6008c06ca9727a2b8ce0fdbf367afc0f7d6df805a2aac968a5b095f5

test:
  secret_key_base: e87301a34d6aab105f3b4d7dd6189a29df4c0b5b649bd6a43dbf349a2cda4188ae5df631e19a9ad1f5a40bd5c1dd230c105420784f5c98ba09091ec4893ab9a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
